title: "Myunghyun Ahn"
description: "Who AM I?"

# 테마 설정
remote_theme: just-the-docs/just-the-docs
url: "https://ahnmyunghyun.com"

permalink: pretty

defaults:
  - scope:
      path: "docs"   # docs 폴더 안쪽을 기본 경로로 지정
      type: "pages"
    values:
      layout: "default"

aux_links:
  "Podcast":
    - "https://www.youtube.com/@suddenly-ajussi-podcast"
    - new_tab: true

just_the_docs:
  navigation_depth: 2

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

