title: Myunghyun Ahn
description: Who AM I?
theme: just-the-docs

url: https://ahnwis.github.io

aux_links:
  YT: https://www.youtube.com/@ahnmyunghyun
  Podcast: https://www.youtube.com/@suddenly-ajussi-podcast
